### ISSUE TITLE
Request: share scripts used to generate images

### ISSUE THREAD

**Issue by bishopdynamics** [frederic/superbird-bulkcmd#1]
Thank you for doing all this work! I am super excited to hack away at this device and repurpose it!

Would you mind sharing some scripts to generate the images that you provide?

**Comment by frederic** [comment]
- superbird.bl2.encrypted.bin : dump of hardware partition _boot0_ (mmcblk0boot0)
- superbird.bootloader.img : dump of user partition _bootloader_ (mmcblk0p01)
- superbird.initrd-base.cpio : created by provided script _extract-cpio.sh_
- superbird.initrd.img : created by provided script _pack-initrd.sh_
- superbird.kernel.img : _zImage_ extracted from user partition _boot_a_ (mmcblk0p12) + weird AML modifications  reverted -_-'

**Comment by bishopdynamics** [comment]
My bad, I should have dug deeper. Thank you!
