### ISSUE TITLE
Potential alternative to amlogic usb tool binary

### ISSUE THREAD

**Issue by bishopdynamics** [frederic/superbird-bulkcmd#10]
I started digging into [pyamlboot](https://github.com/superna9999/pyamlboot) and realized we could use it to replace `bin/update`. 

I re-implemented `scripts/upload-kernel.sh` in python as an example, and [posted it here](https://github.com/err4o4/spotify-car-thing-reverse-engineering/issues/18#issuecomment-1291522387)

**Comment by npjohnson** [comment]
Thanks, in this repo we will continue using the host binary. But good work!
