### ISSUE TITLE
Script for reflashing car thing from a dump

### ISSUE THREAD

**Issue by lmore377** [frederic/superbird-bulkcmd#12]
Bootloader partition fails but everything else flashes fine. Double checked by dumping, resetting, then flashing. All settings came back and changes to env were undone.

[undump.txt](https://github.com/frederic/superbird-bulkcmd/files/9887242/undump.txt)

**Comment by lmore377** [comment]
I can also confirm that a clean dump from a brand new car thing can be treated as a factory image. I'm not sure where it pulls the serial number from but it doesn't seem to be from anywhere in flash so it'll always have the correct serial and mac address

**Comment by bishopdynamics** [comment]
I believe the serial number and bluetooth mac address are written to efuses on the SoC
