### ISSUE TITLE
burn-mode.sh fails with '[LUSB]ERR(L814):Fail in [Get] csw, ret=0'

### ISSUE THREAD

**Issue by sgreenlay** [frederic/superbird-bulkcmd#13]
Got a new CarThing, ran through the instructions and hit an error at Step 5:

> ubuntu% sudo ./scripts/burn-mode.sh
> ..
> Transfer Complete! total size is 65536 Bytes
> [update]Run at Addr fffa0000
> AmlUsbRunBinCode:ram_addr=fffa0000
> [LUSB][AMLC]dataSize=16384, offset=65536, seq 0
> [LUSB]requestType=0
> [LUSB]before wait sum
> [LUSB]check sum OKAY
> [LUSB][AMLC]dataSize=49152, offset=393216, seq 1
> [LUSB]requestType=0
> [LUSB]before wait sum
> [LUSB]check sum OKAY
> [LUSB][AMLC]dataSize=16384, offset=229376, seq 2
> [LUSB]requestType=0
> [LUSB]before wait sum
> [LUSB]check sum OKAY
> [LUSB][AMLC]dataSize=49152, offset=180224, seq 3
> [LUSB]requestType=0
> [LUSB]before wait sum
> [LUSB]ERR(L814):Fail in [Get] csw, ret=0
> [LUSB]check sum FAIL
> get cbw failed, want 512, ret -110
> [LUSB]ERR(L1172):fail in parse cmd, ret=-1079

Anyone else run into this?

**Comment by trevorzucker** [comment]
Try in a USB2.0 port. I also have had issues trying to use a Linux VM and WSL.
If you are using Windows, try [this tool](https://github.com/khadas/utils/tree/master/aml-flash-tool/tools)

**Comment by sgreenlay** [comment]
Thanks! After switching to a USB2 cable it worked.
