### ISSUE TITLE
boot _b side

### ISSUE THREAD

**Issue by mogorman** [frederic/superbird-bulkcmd#15]
The latest binaries from spotify are on my _b partition not the _a.  I tried editing the `initird/init` and `env.txt` and rebuilding but on boot the superbird binary doesnt seem to start correctly. Is there a step im missing? or is there a way I can force spotify to write the latest firmware to the _a side of the device?

Thanks

**Comment by fonix232** [comment]
To swap boot slots, you need to edit the `active_slot` env var. The accepted values are `_a` and `_b`.

Execute the following command (replacing the indicated `[value]` with your selected slot):

```
./bin/update bulkcmd 'amlmmc env'
./bin/update bulkcmd 'setenv active_slot [value]'
./bin/update bulkcmd 'env save'
```
