### ISSUE TITLE
Strictly Linux?

### ISSUE THREAD

**Issue by risograph** [frederic/superbird-bulkcmd#3]
I am interested in running this but I wanted to know if this was also possible using a macOS device, considering certain similarities.

As of right now I don't see a specific reason why it wouldn't work, and would be happy to attempt and let you all know if it does or not if it isn't known already.

**Comment by npjohnson** [comment]
It can't work. At least not with the publicly available tools.

Amlogic only releases their update tool to interface with burn mode for Linux, and Windows versions exist. It is pre built, not open source.
