### ISSUE TITLE
`upload-kernel.sh` failing

### ISSUE THREAD

**Issue by Merlin04** [frederic/superbird-bulkcmd#5]
I'm trying to follow the steps as outlined in the readme - I am able to run all of the previous scripts, but `upload-kernel.sh` gives an error. When I plug the device in to my computer after I run step 6, it boots normally (which I presume is not intended), and when I run the upload kernel script I get this output:

> AmlUsbBulkCmd[amlmmc env]
> [AmlUsbRom]Inf:bulkInReply success
> ..
> Transfer Complete! total size is 570 Bytes
> AmlUsbBulkCmd[env import -t 0x13000000 0x23a]
> [AmlUsbRom]Inf:bulkInReply success
> ......................................................................................................................................................................................................................................................................................................................................................................................................................................
> Transfer Complete! total size is 13780992 Bytes
> ......................................................................................
> Transfer Complete! total size is 2789041 Bytes
> Booting...
> AmlUsbBulkCmd[booti 0x01080000 0x13000000]
> usbReadFile len=512,ret=-6 error_msg=No such device or address
> [AmlUsbRom]Err:return len=-1 < strLenBusy 11
> [AmlUsbRom]Inf:bulkInReply 
> ERR: AmlUsbBulkCmd failed!

When I boot it with the buttons 1 and 4 held down and manually activate burn mode, then run the script, I also get an error, although a different one:

> AmlUsbBulkCmd[amlmmc env]
> [AmlUsbRom]Inf:bulkInReply success
> ..
> Transfer Complete! total size is 570 Bytes
> AmlUsbBulkCmd[env import -t 0x13000000 0x23a]
> [AmlUsbRom]Inf:bulkInReply success
> ......................................................................................................................................................................................................................................................................................................................................................................................................................................
> Transfer Complete! total size is 13780992 Bytes
> ......................................................................................
> Transfer Complete! total size is 2789041 Bytes
> Booting...
> AmlUsbBulkCmd[booti 0x01080000 0x13000000]
> [AmlUsbRom]Inf:bulkInReply failed:
> ERR: AmlUsbBulkCmd failed!

**Comment by frederic** [comment]
The last command (*booti*) in script upload-kernel.sh always returns an error message, even when it runs as expected : I think it's due to fact that this command jumps to the kernel, so I cannot return properly.

>When I plug the device in to my computer after I run step 6, it boots normally (which I presume is not intended), and when I run the upload kernel script I get this output

It is actually intended to boot normally : this procedure is just meant to enable ADB access on original firmware.

>When I boot it with the buttons 1 and 4 held down and manually activate burn mode, then run the script, I also get an error, although a different one:

This cannot work : the reason is, when you use the bootrom usb mode (i.e. hold buttons 1&4), U-Boot interrupts initialization to start burning mode immediately. So if you attempt to boot a kernel from there, it will fail since the board as not been fully initialized.

**Comment by H4CK3RxDE** [comment]
Unfortunately, I don't have ADB access after running `upload-kernel.sh`. When I run `dmesg` I get the following output:
`usbfs: process xxxx (update) did not claim Interface 0 before use`
This repeats several times, where xxxx is the process ID.
This issue follows at the end:
`USB disconnected, device number 1`

**Comment by Merlin04** [comment]
@H4CK3RxDE a bit late to this but I was getting the same error, switching to using https://github.com/bishopdynamics/superbird-tool instead of this repo's script fixed it
