### ISSUE TITLE
Method to return to previous firmware

### ISSUE THREAD

**Issue by lmore377** [frederic/superbird-bulkcmd#6]
I was messing around with the car thing a while back and I figured out how to switch between the previous and current firmware versions. You pretty much just reboot it 8 times without actually letting it completely start up and it'll switch back to the previous version of the firmware that was on there. If you do it again it switches to the most recent you had installed.

Originally posted here: https://github.com/err4o4/spotify-car-thing-reverse-engineering/issues/5

**Comment by lmore377** [comment]
Now that we have uboot access I'm sure there's a much easier way to do it but just thought I'd mention this

**Comment by npjohnson** [comment]
appreciate it, yeah, it's rescue party doing that.
