### ISSUE TITLE
Disable booting to UBoot burn mode

### ISSUE THREAD

**Issue by Bankst** [frederic/superbird-bulkcmd#8]
Is there a way to effectively undo what was done by the burn-mode script?

**Comment by Borillion** [comment]
I believe that is what this script is for :)

[scripts/uboot-continue.sh](https://github.com/frederic/superbird-bulkcmd/blob/main/scripts/uboot-continue.sh) : Exit U-Boot USB Burning mode and continue default boot sequence

**Comment by npjohnson** [comment]
Just reverse what was done and remove that from env

**Comment by Merlin04** [comment]
how do you do that?
