### ISSUE TITLE
scripts/update-kernel.sh fails to boot device

### ISSUE THREAD

**Issue by whitea17** [frederic/superbird-bulkcmd#9]
Hi,
I am trying to gain a root shell via ADB without taking the device apart.  Here are the steps I took:
1. Place the device in flash mode with key combo at power on.
2. Run `./scripts/burn-mode.sh`
3. Run `./scripts/update-kernel.sh`

When I follow the above steps, I get the following error message and the device remains in burn-in mode.
```./scripts/upload-kernel.sh 
AmlUsbBulkCmd[amlmmc env]
[AmlUsbRom]Inf:bulkInReply success
..
Transfer Complete! total size is 570 Bytes
AmlUsbBulkCmd[env import -t 0x13000000 0x23a]
[AmlUsbRom]Inf:bulkInReply success
......................................................................................................................................................................................................................................................................................................................................................................................................................................
Transfer Complete! total size is 13780992 Bytes
......................................................................................
Transfer Complete! total size is 2788757 Bytes
Booting...
AmlUsbBulkCmd[booti 0x01080000 0x13000000]
[AmlUsbRom]Inf:bulkInReply failed:
ERR: AmlUsbBulkCmd failed!
```

Additional debugging steps taken:
- Commenting out the "booti" command in the `upload-kernel.sh`, removes the error message but the device does not boot (no boot command given, duh)
  - Running `./scripts/uboot-continue.sh` after step 2, the device boots into default state but shows this message:
```AmlUsbBulkCmd[mw.b 0x17f89754 1]
[AmlUsbRom]Err:return len=0 < strLenBusy 11
[AmlUsbRom]Inf:bulkInReply 
ERR: AmlUsbBulkCmd failed!
```
 - Seems like the issue is related to boot commands
- Running `./scripts/disable-avb2.sh`, power cycling, then following attempted steps again, produces the same error message.
- Running `./scripts/extract-cpio.sh` and `./scripts/pack-initrd.sh`,  power cycling, then following attempted steps again, produces the same error message.

Any thoughts on how to fix this?

**Comment by frederic** [comment]
>Run ./scripts/burn-mode.sh
>Run ./scripts/update-kernel.sh

You cannot chain these two commands, it will fail.
To execute update-kernel.sh, you must boot normally, with the device connected to your computer via USB cable.

**Comment by whitea17** [comment]
> > Run ./scripts/burn-mode.sh
> > Run ./scripts/update-kernel.sh
> 
> You cannot chain these two commands, it will fail. To execute update-kernel.sh, you must boot normally, with the device connected to your computer via USB cable.

As soon as I boot normally, the USB device disappears. Is this step (below) a requirement or optional (I didn't do it, thinking I could just use `./scripts/burn-mode.sh` every time, my main pwr source will be a pc)?
```
./bin/update bulkcmd 'amlmmc env'
./bin/update bulkcmd 'setenv storeargs ${storeargs} run update\;'
./bin/update bulkcmd 'env save'
```

Also, from the readme...

> Boot kernel from USB to enable ADB access
> Once the device in USB burning mode, the script [scripts/upload-kernel.sh](https://github.com/frederic/superbird-> bulkcmd/blob/main/scripts/upload-kernel.sh) can upload a Linux kernel image and boot it.

Edit: Qouted info from readme

**Comment by frederic** [comment]
>Is this step (below) a requirement or optional (I didn't do it, thinking I could just use ./scripts/burn-mode.sh every time, my main pwr source will be a pc)?
This step is required to execute upload-kernel.sh. Otherwise, it doesn't work. Please see #5 .

>Also, from the readme...
This implies the previous guide was followed, including the step that modifies the env.

**Comment by lmore377** [comment]
> As soon as I boot normally, the USB device disappears. Is this step (below) a requirement or optional (I didn't do it, thinking I could just use `./scripts/burn-mode.sh` every time, my main pwr source will be a pc)?

It's not optional unfortunately. After doing that step the car thing should get stuck on the spotify logo when booting "normally" and from there you can run upload-kernel.sh. From what I can tell, burn-mode.sh just straight up doesn't initialize some critical parts like the display so uboot just can't start the kernel.
